export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART = 'GET_CART';
export const ITEM_QUANTITY = 'ITEM_QUANTITY';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CART_ITEM_COUNT = 'CART_ITEM_COUNT';
export const CART_TOTAL_AMOUNT = 'CART_TOTAL_AMOUNT';